| check                                   | result | detail                                                                                                                                                                |
| --------------------------------------- | ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Migrations 0021-0027 applied            | ACTION | missing: 0021, 0022, 0023, 0024, 0025, 0026                                                                                                                           |
| At least one approved CEO/admin account | ACTION | could not read profiles approved admin account(s)                                                                                                                     |
| Emails actually sending                 | ACTION | could not read the email queue - notifications table columns are: id, org_id, recipient_id, kind, title, body, link_type, link_id, is_read, email_sent_at, created_at |
| Instant email trigger (0020)            | ACTION | pg_net OFF, trigger MISSING                                                                                                                                           |
| Worker secret stored in Vault           | ACTION | absl_worker_secret not found - instant sends are refused until it exists                                                                                              |
| 5-minute retry cron for emails          | ACTION | pg_cron not enabled (fine only if an outside scheduler calls send-notifications)                                                                                      |
| Live updates (realtime) on              | ACTION | enabled for: none                                                                                                                                                     |
| Every login has a profile               | OK     | 0 login(s) with no profile row                                                                                                                                        |
| File buckets are private                | OK     | all ticket buckets private                                                                                                                                            |
| Unverified logins                       | INFO   | 0 of 1 logins have not verified their email                                                                                                                           |
| Auto-approved email domains             | INFO   | none - customers on these domains get in without review                                                                                                               |